apiVersion: v1
kind: Namespace
metadata:
  name: octocat-generator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: octocat-generator
spec:
  selector:
    matchLabels:
      app: octocat-generator
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: octocat-generator
    spec:
      containers:
      - name: octodemo-generator
        image: jonico/octocat-generator
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: octocat-generator
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    protocol: TCP
    targetPort: 4000
  selector:
    app: octocat-generator
  sessionAffinity: None
  type: LoadBalancer
